version: '2'

services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - "9000:80"
    volumes:
      - "/Users/yuanying/Documents:/Users/yuanying/Documents"
      - "/Users/yuanying/Downloads:/Users/yuanying/Downloads"
      - "/Users/yuanying/Pictures:/Users/yuanying/Pictures"
      - "/Users/yuanying/.cache:/Users/yuanying/.cache"
      - "./nginx:/etc/nginx"
    environment:
      - "LANG=C.UTF-8"
  app:
    image: yuanying/aphrael:dev
    command: bundle exec thin -R config.ru -p 9292 -e production start
    ports:
      - "9292:9292"
    volumes:
      - "/Users/yuanying/Documents:/Users/yuanying/Documents"
      - "/Users/yuanying/Downloads:/Users/yuanying/Downloads"
      - "/Users/yuanying/Pictures:/Users/yuanying/Pictures"
      - "/Users/yuanying/.cache:/Users/yuanying/.cache"
    environment:
      - "RACK_ENV=production"
      - "LANG=C.UTF-8"
