
image_dirs:
  - path: /Users/yuanying/Pictures
    name: My Pictures
  - path: /Users/yuanying/Documents
    name: My Documents
  - path: /Users/yuanying/Downloads
    name: My Downloads

tmp_dir: /Users/yuanying/.cache
